In [75]:
words = open('/Users/justlikethat/Downloads/names.txt', 'r').read().splitlines()

In [76]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt # for making figures
%matplotlib inline

In [77]:
words = [w.lower() for w in words]

In [118]:
words = open('/Users/justlikethat/Downloads/names.txt', 'r').read().splitlines()
# build the vocabulary of characters and mappings to/from integers
chars = sorted( list(set(''.join(words))) )
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
# build the dataset
block_size = 3 # context length: how many characters do we take to predict the next one?

def build_dataset(words):  
  X, Y = [], []
  for w in words:

    #print(w)
    context = [0] * block_size
    for ch in w + '.':
      ix = stoi[ch]
      X.append(context)
      Y.append(ix)
      #print(''.join(itos[i] for i in context), '--->', itos[ix])
      context = context[1:] + [ix] # crop and append

  X = torch.tensor(X)
  Y = torch.tensor(Y)
  print(X.shape, Y.shape)
  return X, Y
random.seed(42)
random.shuffle(words)
n1 = int(0.8*len(words))
n2 = int(0.9*len(words))
Xtr, Ytr = build_dataset(words[:n1])
Xdev, Ydev = build_dataset(words[n1:n2])
Xte, Yte = build_dataset(words[n2:])
emb.view(-1, 6)

torch.Size([106825, 3]) torch.Size([106825])
torch.Size([13359, 3]) torch.Size([13359])
torch.Size([13374, 3]) torch.Size([13374])


tensor([[-0.0517, -0.7716, -0.0517, -0.7716, -0.0517, -0.7716],
        [-0.0517, -0.7716, -0.0517, -0.7716,  0.3289, -1.0988],
        [-0.0517, -0.7716,  0.3289, -1.0988,  1.4435,  0.7789],
        [ 0.3289, -1.0988,  1.4435,  0.7789, -0.1053, -1.3441],
        [ 1.4435,  0.7789, -0.1053, -1.3441,  1.4435,  0.7789],
        [-0.1053, -1.3441,  1.4435,  0.7789, -0.7820,  1.0461],
        [ 1.4435,  0.7789, -0.7820,  1.0461, -0.0723, -1.5007],
        [-0.7820,  1.0461, -0.0723, -1.5007, -1.2980, -2.3730],
        [-0.0517, -0.7716, -0.0517, -0.7716, -0.0517, -0.7716],
        [-0.0517, -0.7716, -0.0517, -0.7716,  0.3289, -1.0988],
        [-0.0517, -0.7716,  0.3289, -1.0988, -1.2980, -2.3730],
        [ 0.3289, -1.0988, -1.2980, -2.3730, -0.5295, -1.2524],
        [-1.2980, -2.3730, -0.5295, -1.2524, -1.2980, -2.3730],
        [-0.5295, -1.2524, -1.2980, -2.3730, -0.2178, -1.5761],
        [-1.2980, -2.3730, -0.2178, -1.5761,  1.4435,  0.7789],
        [-0.2178, -1.5761,  1.4435,  0.7

In [107]:
# build the dataset
block_size = 3 # context length: how many characters do we take to predict the next one?

def build_dataset(words):  
  X, Y = [], []
  for w in words:

    #print(w)
    context = [0] * block_size
    for ch in w + '.':
      ix = stoi[ch]
      X.append(context)
      Y.append(ix)
      #print(''.join(itos[i] for i in context), '--->', itos[ix])
      context = context[1:] + [ix] # crop and append

  X = torch.tensor(X)
  Y = torch.tensor(Y)
  print(X.shape, Y.shape)
  return X, Y
random.seed(42)
random.shuffle(words)
n1 = int(0.8*len(words))
n2 = int(0.9*len(words))
Xtr, Ytr = build_dataset(words[:n1])
Xdev, Ydev = build_dataset(words[n1:n2])
Xte, Yte = build_dataset(words[n2:])
C = torch.randn((27, 2))


... ---> t
..t ---> i
.ti ---> k
tik ---> i
iki ---> s
kis ---> h
ish ---> a
sha ---> .
... ---> t
..t ---> a
.ta ---> m
tam ---> a
ama ---> r
mar ---> i
ari ---> o
rio ---> .
... ---> s
..s ---> o
.so ---> n
son ---> n
onn ---> y
nny ---> .
... ---> d
..d ---> a
.da ---> p
dap ---> h
aph ---> i
phi ---> n
hin ---> e
ine ---> .
... ---> d
..d ---> o
.do ---> m
dom ---> e
ome ---> n
men ---> i
eni ---> c
nic ---> k
ick ---> .


In [90]:
# build the dataset
block_size = 3 # context length: how many characters do we take to predict the next one?

def build_dataset(words):  
  X, Y = [], []
  for w in words:

    #print(w)
    context = [0] * block_size
    for ch in w + '.':
      ix = stoi[ch]
      X.append(context)
      Y.append(ix)
      #print(''.join(itos[i] for i in context), '--->', itos[ix])
      context = context[1:] + [ix] # crop and append

  X = torch.tensor(X)
  Y = torch.tensor(Y)
  print(X.shape, Y.shape)
  return X, Y
random.seed(42)
random.shuffle(words)
n1 = int(0.8*len(words))
n2 = int(0.9*len(words))
Xtr, Ytr = build_dataset(words[:n1])
Xdev, Ydev = build_dataset(words[n1:n2])
Xte, Yte = build_dataset(words[n2:])
emb.view(39, 6)

torch.Size([43, 3])
torch.Size([43])
torch.Size([106867, 3]) torch.Size([106867])
torch.Size([43, 3])
torch.Size([43])
torch.Size([13308, 3]) torch.Size([13308])
torch.Size([43, 3])
torch.Size([43])
torch.Size([13383, 3]) torch.Size([13383])
torch.Size([43, 3])
torch.Size([43])


In [85]:
X.shape, X.dtype, Y.shape, Y.dtype

(torch.Size([43, 3]), torch.int64, torch.Size([43]), torch.int64)

In [108]:
C = torch.randn((27, 2))

In [109]:
emb = C[X]

In [110]:
emb.shape

torch.Size([39, 3, 2])

In [95]:
emb.shape

torch.Size([106867, 3, 2])

In [115]:
emb

tensor([[[-0.0517, -0.7716],
         [-0.0517, -0.7716],
         [-0.0517, -0.7716]],

        [[-0.0517, -0.7716],
         [-0.0517, -0.7716],
         [ 0.3289, -1.0988]],

        [[-0.0517, -0.7716],
         [ 0.3289, -1.0988],
         [ 1.4435,  0.7789]],

        [[ 0.3289, -1.0988],
         [ 1.4435,  0.7789],
         [-0.1053, -1.3441]],

        [[ 1.4435,  0.7789],
         [-0.1053, -1.3441],
         [ 1.4435,  0.7789]],

        [[-0.1053, -1.3441],
         [ 1.4435,  0.7789],
         [-0.7820,  1.0461]],

        [[ 1.4435,  0.7789],
         [-0.7820,  1.0461],
         [-0.0723, -1.5007]],

        [[-0.7820,  1.0461],
         [-0.0723, -1.5007],
         [-1.2980, -2.3730]],

        [[-0.0517, -0.7716],
         [-0.0517, -0.7716],
         [-0.0517, -0.7716]],

        [[-0.0517, -0.7716],
         [-0.0517, -0.7716],
         [ 0.3289, -1.0988]],

        [[-0.0517, -0.7716],
         [ 0.3289, -1.0988],
         [-1.2980, -2.3730]],

        [[ 0.3289, -1

In [114]:
emb[:, 0, :]

tensor([[-0.0517, -0.7716],
        [-0.0517, -0.7716],
        [-0.0517, -0.7716],
        [ 0.3289, -1.0988],
        [ 1.4435,  0.7789],
        [-0.1053, -1.3441],
        [ 1.4435,  0.7789],
        [-0.7820,  1.0461],
        [-0.0517, -0.7716],
        [-0.0517, -0.7716],
        [-0.0517, -0.7716],
        [ 0.3289, -1.0988],
        [-1.2980, -2.3730],
        [-0.5295, -1.2524],
        [-1.2980, -2.3730],
        [-0.2178, -1.5761],
        [-0.0517, -0.7716],
        [-0.0517, -0.7716],
        [-0.0517, -0.7716],
        [-0.7820,  1.0461],
        [-0.7730, -0.3765],
        [ 0.1109,  0.1388],
        [-0.0517, -0.7716],
        [-0.0517, -0.7716],
        [-0.0517, -0.7716],
        [ 0.8202,  0.3858],
        [-1.2980, -2.3730],
        [-0.3487,  0.5788],
        [-0.0723, -1.5007],
        [ 1.4435,  0.7789],
        [-0.0517, -0.7716],
        [-0.0517, -0.7716],
        [-0.0517, -0.7716],
        [ 0.8202,  0.3858],
        [-0.7730, -0.3765],
        [-0.5295, -1

In [112]:
emb[:, 1, :]

tensor([[-0.0517, -0.7716],
        [-0.0517, -0.7716],
        [ 0.3289, -1.0988],
        [ 1.4435,  0.7789],
        [-0.1053, -1.3441],
        [ 1.4435,  0.7789],
        [-0.7820,  1.0461],
        [-0.0723, -1.5007],
        [-0.0517, -0.7716],
        [-0.0517, -0.7716],
        [ 0.3289, -1.0988],
        [-1.2980, -2.3730],
        [-0.5295, -1.2524],
        [-1.2980, -2.3730],
        [-0.2178, -1.5761],
        [ 1.4435,  0.7789],
        [-0.0517, -0.7716],
        [-0.0517, -0.7716],
        [-0.7820,  1.0461],
        [-0.7730, -0.3765],
        [ 0.1109,  0.1388],
        [ 0.1109,  0.1388],
        [-0.0517, -0.7716],
        [-0.0517, -0.7716],
        [ 0.8202,  0.3858],
        [-1.2980, -2.3730],
        [-0.3487,  0.5788],
        [-0.0723, -1.5007],
        [ 1.4435,  0.7789],
        [ 0.1109,  0.1388],
        [-0.0517, -0.7716],
        [-0.0517, -0.7716],
        [ 0.8202,  0.3858],
        [-0.7730, -0.3765],
        [-0.5295, -1.2524],
        [-0.4677, -0

In [116]:
emb.view(39, 6)

tensor([[-0.0517, -0.7716, -0.0517, -0.7716, -0.0517, -0.7716],
        [-0.0517, -0.7716, -0.0517, -0.7716,  0.3289, -1.0988],
        [-0.0517, -0.7716,  0.3289, -1.0988,  1.4435,  0.7789],
        [ 0.3289, -1.0988,  1.4435,  0.7789, -0.1053, -1.3441],
        [ 1.4435,  0.7789, -0.1053, -1.3441,  1.4435,  0.7789],
        [-0.1053, -1.3441,  1.4435,  0.7789, -0.7820,  1.0461],
        [ 1.4435,  0.7789, -0.7820,  1.0461, -0.0723, -1.5007],
        [-0.7820,  1.0461, -0.0723, -1.5007, -1.2980, -2.3730],
        [-0.0517, -0.7716, -0.0517, -0.7716, -0.0517, -0.7716],
        [-0.0517, -0.7716, -0.0517, -0.7716,  0.3289, -1.0988],
        [-0.0517, -0.7716,  0.3289, -1.0988, -1.2980, -2.3730],
        [ 0.3289, -1.0988, -1.2980, -2.3730, -0.5295, -1.2524],
        [-1.2980, -2.3730, -0.5295, -1.2524, -1.2980, -2.3730],
        [-0.5295, -1.2524, -1.2980, -2.3730, -0.2178, -1.5761],
        [-1.2980, -2.3730, -0.2178, -1.5761,  1.4435,  0.7789],
        [-0.2178, -1.5761,  1.4435,  0.7